### ISSUE TITLE
Export DNS Records does not return json

### ISSUE THREAD

**Issue by pstadt** [fayland/perl-MojoX-CloudFlare-Simple#2]
Hello
While playing with the api I found that
https://api.cloudflare.com/#dns-records-for-a-zone-export-dns-records
does not return json, it returns application/octet-stream.

I worked around this using this little patch:
[mcfs.patch.txt](https://github.com/fayland/perl-MojoX-CloudFlare-Simple/files/2522632/mcfs.patch.txt)

I am not sure if this sufficient, because I do not know much about the api's cornercases.
Feel free to use my patch or write a better one.

**Comment by fayland** [comment]
Yes, that's great patch. just released a new version and many thanks!
